### PR TITLE
Added force update and clear milestone features

### PR DESCRIPTION
**Pull request by ltshb**
Now we can configure the action to force the update of the milestones if it is already set and also to clear the milestone if no milestone is match from the PR base/head branches.

### CODE REVIEW

**Comment by ltshb** [comment]
@iyu Hello it would be great if you could have a look at this PR. Best regards

**Comment by ltshb** [comment]
@iyu thanks a lot for your very quick response !

**Comment by ltshb** [comment]
@iyu Thanks a lot for merging this, when do you plan to create a new release with this functionality ?

**Comment by iyu** [comment]
@ltshb Thank you for waiting. Release is now complete!

**Pull request merged**
